### ISSUE TITLE
Okta Verify MFA prompts twice

### ISSUE THREAD

**Issue by hiruna** [Versent/saml2aws#507]
Here is a copy of my config
```
account {
  URL: <okta_aws_app_url>
  Username: <my_email>
  Provider: Okta
  MFA: Auto
  SkipVerify: false
  AmazonWebservicesURN: urn:amazon:webservices
  SessionDuration: 3600
  Profile: default
  RoleARN: 
  Region: 
}
``` 
Upon executing `saml2aws login`, the cli prompts me for the MFA twice before listing the roles:
![image](https://user-images.githubusercontent.com/3973928/82966260-d3674180-a00d-11ea-9fe4-bd053eab599b.png)

This also occurs when using the code verification option (instead of the push).
